name: CI

on:
  push:
    tags:
      - "v*.*.*"

env:
  NODE_VERSION: "18.19.0"
  NPM_ORG_NAMESPACE: "vela-ventures"
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish-package:
    runs-on: ubuntu-latest
    dependencies:
        - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org/"

      - name: Publish
        run: npm publish


  build:
    image: ubuntu-latest
    stage: build
    script:
        - node --version
        - npm --version
        - npm ci
        - npm run build -- --watch=false
        - npm run build:prod

